# Sets default memory used for gradle commands. Can be overridden by user or command line properties.
# This is required to provide enough memory for the Minecraft decompilation process.
org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false


## Environment Properties

minecraft_version=1.20.1
minecraft_version_range=[1.20.1,1.21)
forge_version=47.2.0
forge_version_range=[47,)
loader_version_range=[47,)

mapping_channel=parchment
mapping_version=2023.09.03-1.20.1

# Tetra mod
tetra_version=6912921
mutil_version=6418901

# Addons
aof_version=6510711
cobweb_version=6089406
soul_fire_d_version=6248077
curios_version=6418456
sofr_version=6778071

## Mod Properties
mod_id=tetra_re_enlarged
mod_name=Tetra: Re-Enlarged
mod_license=All Rights Reserved
mod_version=1.1.0
mod_group_id=net.gamerk_2.tetra_re_enlarged
mod_authors=GamerK_2
mod_description=Remake version of "Tetra: Enlarged" mod. Adds lager 32x version of some modular items.